# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e05a02543cc9b7efd865dd1b2cd7ac851d91bb9bd0f0bf0342685fec85c3e0f1756d6e0580ff804cc61263e0c137809afbcbaafd845759af5d01b1ef731c329c

test:
  secret_key_base: e197e0cdb4c6da6634b9ccfff523741771e228b4fb36d6c00e3f80c4d101fdeff25d7a626f942735db30f4190aab50fcec375267f12b9825f858b15d67a488b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
